package com.gios.lightnonogram.game

import java.util.Base64

/** One puzzle as it ships in the bundled pack. */
data class Puzzle(
    val id: String,
    val width: Int,
    val height: Int,
    val bits: String,
    val difficulty: Int,
    val passes: Int,
    /** Design name, e.g. "heart". Hidden until solved — it's the reveal. */
    val title: String?,
) {
    /** Decode to a 0/1 array. Cheap enough to do on demand; no need to cache. */
    fun solution(): IntArray {
        val bytes = Base64.getDecoder().decode(bits)
        val n = width * height
        require(bytes.size >= (n + 7) / 8) { "bit payload too short for ${width}x$height" }
        return IntArray(n) { i -> (bytes[i / 8].toInt() shr (7 - (i % 8))) and 1 }
    }

    fun newBoard(): Board = Board(width, height, solution())
}

/**
 * Minimal reader for the pack JSON that `picross-gen` emits.
 *
 * Hand-rolled rather than pulling in kotlinx-serialization. The schema is fixed,
 * flat, and generated by code in this same repo, so a regex reader is honest
 * here — and it keeps one more dependency off a classpath the Light SDK
 * deliberately restricts.
 *
 * If the pack format ever grows nesting, throw this away and use
 * kotlinx-serialization (it *is* allow-listed).
 */
object PackReader {

    private val puzzleObj = Regex("""\{[^{}]*"bits"\s*:\s*"[^"]*"[^{}]*}""")

    fun parse(json: String): List<Puzzle> =
        puzzleObj.findAll(json).map { m ->
            val o = m.value
            Puzzle(
                id = str(o, "id") ?: error("puzzle missing id"),
                width = int(o, "w") ?: error("puzzle missing w"),
                height = int(o, "h") ?: error("puzzle missing h"),
                bits = str(o, "bits") ?: error("puzzle missing bits"),
                difficulty = int(o, "difficulty") ?: 1,
                passes = int(o, "passes") ?: 0,
                title = str(o, "source"),
            )
        }.toList()

    private fun str(obj: String, key: String): String? =
        Regex("\"$key\"\\s*:\\s*\"([^\"]*)\"").find(obj)?.groupValues?.get(1)

    private fun int(obj: String, key: String): Int? =
        Regex("\"$key\"\\s*:\\s*(-?[0-9]+)").find(obj)?.groupValues?.get(1)?.toIntOrNull()
}

/**
 * Which puzzles the player has finished.
 *
 * Stored as a comma-joined id list. Ids are content hashes from the generator,
 * so regenerating the pack doesn't wipe anyone's progress — only genuinely
 * changing a picture does.
 */
data class Progress(val completed: Set<String> = emptySet()) {

    fun with(id: String): Progress =
        if (id in completed) this else Progress(completed + id)

    fun has(id: String): Boolean = id in completed

    fun encode(): String = completed.sorted().joinToString(",")

    fun countIn(puzzles: List<Puzzle>): Int = puzzles.count { it.id in completed }

    companion object {
        fun decode(raw: String?): Progress {
            if (raw.isNullOrBlank()) return Progress()
            return Progress(raw.split(",").map { it.trim() }.filter { it.isNotEmpty() }.toSet())
        }
    }
}
