package com.gios.lightnonogram.data

// GENERATED by picross-gen — do not edit.
// Source of truth is art/icons-10.txt. Regenerate with:
//   ./gradlew run --args="bundle --art ../../art/icons-10.txt --kotlin <path>"
//
// Compiled in rather than loaded from assets because the Light SDK blocks
// android.content.Context, and therefore AssetManager.

/** 34 hand-drawn puzzles, all verified uniquely solvable. */
internal const val BUNDLED_PACK_15: String = """{
  "id": "bundled-15",
  "name": "Pictures 15",
  "version": 1,
  "license": "CC0-1.0",
  "puzzles": [
    {"id":"4e47b615f014","w":15,"h":15,"bits":"4A/gP+D/6//////99/HH99//////6/+D/gP4A4A=","difficulty":1,"passes":2,"source":"butterfly"},
    {"id":"3e3436209660","w":15,"h":15,"bits":"AQACAERAiIP/j/+//+/7//+/7//////////AAAA=","difficulty":1,"passes":2,"source":"cake"},
    {"id":"f2271540d365","w":15,"h":15,"bits":"AAEHBw4ePj58/f3/////7+//////////4AAAAAA=","difficulty":1,"passes":2,"source":"crown"},
    {"id":"ced3a46e8ea8","w":15,"h":15,"bits":"AAH////+473He47///////+473He47/////AAAA=","difficulty":1,"passes":2,"source":"dice"},
    {"id":"1c5ad8a3db69","w":15,"h":15,"bits":"AABAEMBhwcP/5/////f37+/////+47b+x/8AAAA=","difficulty":2,"passes":3,"source":"cat"},
    {"id":"a10f2523fa80","w":15,"h":15,"bits":"AAH//8B/Y344/Pn7G/gP///////////////AAAA=","difficulty":1,"passes":3,"source":"envelope"},
    {"id":"7f6c5aed3edf","w":15,"h":15,"bits":"AQAHAB8AfwH/B/8f/3//39+/v//+fPz5/////4A=","difficulty":1,"passes":3,"source":"house"},
    {"id":"3c2436f0a1fb","w":15,"h":15,"bits":"AAAPgH/B/8f/3////+/7B8AIgBEAPgD+A/4AAAA=","difficulty":2,"passes":3,"source":"mushroom"},
    {"id":"125ba3b37ae6","w":15,"h":15,"bits":"AABgMODh/////Pn27e3b58///Pvh//H/wYMOA4A=","difficulty":2,"passes":3,"source":"owl"},
    {"id":"fef4ed16aa0f","w":15,"h":15,"bits":"CCAQQH/B/8N9h/8OOh/8f/3f37+4fwDGAYwHvAA=","difficulty":3,"passes":3,"source":"robot"},
    {"id":"2da52b6bdde7","w":15,"h":15,"bits":"AQADAAcADwAfAD8AfwD///7/+P/g/4AABxwAAAA=","difficulty":2,"passes":3,"source":"sailboat"},
    {"id":"5e1ae6a85cd5","w":15,"h":15,"bits":"AAAPgH/B/8f/3//3/efz7+7/+P/g/4MBjgOAAAA=","difficulty":2,"passes":3,"source":"turtle"},
    {"id":"fff772c61bb7","w":15,"h":15,"bits":"AAAPgH/B/8f/3////4CAAQACAAQACYARAD4AAAA=","difficulty":3,"passes":3,"source":"umbrella"},
    {"id":"f6ef8f80c5bd","w":15,"h":15,"bits":"AQAHAB8AAAD+B/8f/3//7////f/x/8cB3gPAAAA=","difficulty":2,"passes":3,"source":"whale"},
    {"id":"cd6e6acf1ded","w":15,"h":15,"bits":"AcADgwcGDjwceDjwcfDnf/gDgAcADgD/gf8AAAA=","difficulty":4,"passes":4,"source":"cactus"},
    {"id":"c80b88f7aca1","w":15,"h":15,"bits":"AAAAAD/A/8P/x/+//////////eDyQSSCTweMBgA=","difficulty":3,"passes":4,"source":"car"},
    {"id":"2216feca6bda","w":15,"h":15,"bits":"AAAPgH/B/8f/3/+9/3v/9/3/+f/x/8H/APgAAAA=","difficulty":2,"passes":4,"source":"fish"},
    {"id":"997fbc49b00a","w":15,"h":15,"bits":"AAAfwP/j/+39+/v///////////////226SSAAAA=","difficulty":1,"passes":4,"source":"ghost"},
    {"id":"7d054104ac26","w":15,"h":15,"bits":"AABwcfH3/////////7/+P/g/4D+APgA4ACAAAAA=","difficulty":3,"passes":4,"source":"heart"},
    {"id":"d3ec054f992b","w":15,"h":15,"bits":"B8A/4P/j/+f/z/+P/g/4D+AfwB8AfwB8AfwB8AA=","difficulty":3,"passes":4,"source":"lightbulb"},
    {"id":"2da3b6287745","w":15,"h":15,"bits":"D+B/8f/3//3He47///////+fz4C7g4f/x/8D+AA=","difficulty":3,"passes":4,"source":"smiley"},
    {"id":"c46a2eb0bee1","w":15,"h":15,"bits":"AAAYwBEAFAD/g4OO45tnNE53OHDgf4P/7//AAAA=","difficulty":4,"passes":4,"source":"snail"},
    {"id":"56bec6c92987","w":15,"h":15,"bits":"B8AYwDGAPgA4B/8A4AHA44/HH447vuP/gfwAAAA=","difficulty":5,"passes":5,"source":"anchor"},
    {"id":"5b182cd5e81f","w":15,"h":15,"bits":"AAAfwP/jwe4g+EDwgeHzwAeAD4A7weP/gfwAAAA=","difficulty":5,"passes":5,"source":"clock"},
    {"id":"faf634beb434","w":15,"h":15,"bits":"AAAAAf+D/wcDjgOcBzgOcDj/wP8A/AAAAfgAAAA=","difficulty":4,"passes":5,"source":"cup"},
    {"id":"3b67b674067f","w":15,"h":15,"bits":"D+B/8fAHgA4AHAA4AHAA4AHAA8AD4AP/gfwAAAA=","difficulty":4,"passes":5,"source":"moon"},
    {"id":"7ec4e54f44aa","w":15,"h":15,"bits":"MBjweeDxgMAAGAD8B/gPwAYfwP/j/+f/x/8H/AA=","difficulty":5,"passes":5,"source":"paw"},
    {"id":"581d995d69f2","w":15,"h":15,"bits":"B8AfwHvA1YH/A/4P/jwecBzgOcBx/2H8BwceDwA=","difficulty":5,"passes":5,"source":"penguin"},
    {"id":"0708ceaa8363","w":15,"h":15,"bits":"AQAHAB8AawDWAawD+A/4P/j/+3/efzD+AYwEBAA=","difficulty":4,"passes":5,"source":"rocket"},
    {"id":"2a1d996b13d3","w":15,"h":15,"bits":"AQAHAB8AfwH/B/8f/3//P/g/4D+AHAA4AHAD+AA=","difficulty":4,"passes":5,"source":"tree"},
    {"id":"16115c0c6e49","w":15,"h":15,"bits":"AYACACTA/8P/z////////////f/x/8GDAAIAAAA=","difficulty":3,"passes":6,"source":"apple"},
    {"id":"ee5a31b719f5","w":15,"h":15,"bits":"AAAD4B/g/8P/j78f/j/8P/A/wD8APABgAYAAAAA=","difficulty":4,"passes":6,"source":"bird"},
    {"id":"a2280ca9347c","w":15,"h":15,"bits":"AAAfgGGBgYMDAwwD8AGAAwAHgAwAHgAwAHAAAAA=","difficulty":5,"passes":7,"source":"key"},
    {"id":"df2545eb4e98","w":15,"h":15,"bits":"AQAfwH/BwcMBjCGY4zCGMBhwcH+AfwAQAHAB8AA=","difficulty":5,"passes":16,"source":"flower"}
  ]
}
"""
