package nonogram

import java.io.File
import java.security.MessageDigest

data class PuzzleRecord(
    val id: String,
    val width: Int,
    val height: Int,
    val bits: String,
    val difficulty: Int,
    val passes: Int,
    val source: String?,
)

data class Pack(
    val id: String,
    val name: String,
    val version: Int,
    val license: String,
    val puzzles: List<PuzzleRecord>,
)

/**
 * Writes the JSON the app fetches. Hand-rolled rather than pulling in a JSON
 * library: the schema is fixed and tiny, and a zero-dependency generator is one
 * less thing to justify in review.
 */
object PackWriter {

    /** Stable content-addressed id, so regenerating a pack doesn't churn ids. */
    fun puzzleId(bits: String, w: Int, h: Int): String {
        val md = MessageDigest.getInstance("SHA-256")
        val digest = md.digest("$w:$h:$bits".toByteArray())
        return digest.take(6).joinToString("") { "%02x".format(it) }
    }

    fun build(
        packId: String,
        name: String,
        version: Int,
        license: String,
        rated: List<Pair<Candidate, Int>>,
        sourceNames: Map<String, String> = emptyMap(),
    ): Pack {
        val puzzles = rated.map { (cand, tier) ->
            val bits = cand.grid.toBits()
            PuzzleRecord(
                id = puzzleId(bits, cand.grid.width, cand.grid.height),
                width = cand.grid.width,
                height = cand.grid.height,
                bits = bits,
                difficulty = tier,
                passes = cand.passes,
                source = sourceNames[bits],
            )
        }
        return Pack(packId, name, version, license, puzzles)
    }

    /**
     * Emit the pack as a Kotlin source file instead of a JSON asset.
     *
     * The Light SDK blocks `android.content.Context`, which is how you would
     * normally reach `assets`. Rather than gamble on what `SealedLightContext`
     * exposes, the pack is compiled straight into the APK as a string constant:
     * no I/O, no Android API, no runtime failure mode, and the bundled puzzles
     * cannot go missing. It's ~8 KB of source — a rounding error in an APK.
     */
    fun writeKotlin(pack: Pack, file: File, packageName: String, constName: String = "BUNDLED_PACK_JSON") {
        file.parentFile?.mkdirs()
        val json = toJson(pack)
        val text = buildString {
            append("package $packageName\n\n")
            append("// GENERATED by picross-gen — do not edit.\n")
            append("// Source of truth is art/icons-10.txt. Regenerate with:\n")
            append("//   ./gradlew run --args=\"bundle --art ../../art/icons-10.txt --kotlin <path>\"\n")
            append("//\n")
            append("// Compiled in rather than loaded from assets because the Light SDK blocks\n")
            append("// android.content.Context, and therefore AssetManager.\n\n")
            append("/** ${pack.puzzles.size} hand-drawn puzzles, all verified uniquely solvable. */\n")
            append("internal const val $constName: String = \"\"\"")
            // Escaped for a raw string literal: only $ needs care, and " can't
            // appear in a triple-quote run of 3+ (it can't here — JSON strings
            // are short and quote-delimited by construction).
            append(json.replace("\$", "\${'\$'}"))
            append("\"\"\"\n")
        }
        file.writeText(text)
        println("wrote ${file.path} (${file.length()} bytes)")
    }

    fun writePack(pack: Pack, dir: File) {
        dir.mkdirs()
        val f = File(dir, "${pack.id}.json")
        f.writeText(toJson(pack))
        println("wrote ${f.path} (${pack.puzzles.size} puzzles, ${f.length()} bytes)")
    }

    /** Regenerates index.json from every pack file present in [dir]. */
    fun writeIndex(dir: File, baseUrl: String) {
        val packs = dir.listFiles { f -> f.extension == "json" && f.name != "index.json" }
            ?.sortedBy { it.name } ?: emptyList()
        val sb = StringBuilder("[\n")
        packs.forEachIndexed { i, f ->
            val text = f.readText()
            val id = extract(text, "\"id\"")
            val name = extract(text, "\"name\"")
            val version = extract(text, "\"version\"")
            val count = Regex("\"bits\"").findAll(text).count()
            sb.append("  {\"id\":${q(id)},\"name\":${q(name)},\"version\":$version,")
            sb.append("\"count\":$count,\"url\":${q("$baseUrl/${f.name}")}}")
            sb.append(if (i == packs.size - 1) "\n" else ",\n")
        }
        sb.append("]\n")
        File(dir, "index.json").writeText(sb.toString())
        println("wrote ${dir.path}/index.json (${packs.size} packs)")
    }

    private fun extract(json: String, key: String): String {
        val m = Regex("$key\\s*:\\s*(\"([^\"]*)\"|[0-9]+)").find(json)
            ?: return ""
        return m.groupValues[2].ifEmpty { m.groupValues[1] }
    }

    private fun toJson(pack: Pack): String = buildString {
        append("{\n")
        append("  \"id\": ${q(pack.id)},\n")
        append("  \"name\": ${q(pack.name)},\n")
        append("  \"version\": ${pack.version},\n")
        append("  \"license\": ${q(pack.license)},\n")
        append("  \"puzzles\": [\n")
        pack.puzzles.forEachIndexed { i, p ->
            append("    {")
            append("\"id\":${q(p.id)},")
            append("\"w\":${p.width},\"h\":${p.height},")
            append("\"bits\":${q(p.bits)},")
            append("\"difficulty\":${p.difficulty},")
            append("\"passes\":${p.passes}")
            if (p.source != null) append(",\"source\":${q(p.source)}")
            append("}")
            append(if (i == pack.puzzles.size - 1) "\n" else ",\n")
        }
        append("  ]\n}\n")
    }

    private fun q(s: String): String = buildString {
        append('"')
        for (ch in s) when (ch) {
            '"' -> append("\\\"")
            '\\' -> append("\\\\")
            '\n' -> append("\\n")
            '\r' -> append("\\r")
            '\t' -> append("\\t")
            else -> if (ch < ' ') append("\\u%04x".format(ch.code)) else append(ch)
        }
        append('"')
    }
}
