package com.gios.lightnonogram.game

/**
 * Just enough JSON to read the bundled puzzle pack.
 *
 * This exists because of a real crash. The pack used to be pulled apart with a
 * `Regex`, and the pattern contained an unescaped `}`. OpenJDK treats a dangling
 * closing brace as a literal; Android's `Pattern` is ICU-backed and rejects it.
 * The pattern was a `val` on an object, so the failure came out as
 * `ExceptionInInitializerError` the moment the first screen composed — after
 * compiling clean, passing lint, and passing every JVM unit test, because the
 * JVM accepted the pattern the device would not.
 *
 * A character scanner has no dialect to disagree about. It behaves the same on
 * every platform, which for the one code path that must work is worth more than
 * the few lines it costs.
 *
 * Deliberately not kotlinx-serialization: that is allow-listed and would be fine,
 * but this is ~100 lines against a schema generated by code in this same repo,
 * and it keeps the tool's classpath as small as the SDK wants it.
 *
 * Supports objects, arrays, strings with escapes, numbers, `true`, `false` and
 * `null` — the whole of JSON except the parts this format never contains.
 */
internal object MiniJson {

    class SyntaxException(message: String) : IllegalArgumentException(message)

    /** @return a Map, List, String, Long, Double, Boolean, or null. */
    fun parse(text: String): Any? {
        val p = Parser(text)
        val value = p.readValue()
        p.skipWhitespace()
        if (!p.atEnd) p.fail("unexpected trailing content")
        return value
    }

    private class Parser(private val s: String) {
        var pos = 0

        val atEnd: Boolean get() = pos >= s.length

        fun fail(what: String): Nothing =
            throw SyntaxException("$what at offset $pos (…${excerpt()}…)")

        private fun excerpt(): String =
            s.substring(maxOf(0, pos - 20), minOf(s.length, pos + 20))

        fun skipWhitespace() {
            while (pos < s.length && s[pos].isJsonWhitespace()) pos++
        }

        private fun Char.isJsonWhitespace() = this == ' ' || this == '\t' || this == '\n' || this == '\r'

        private fun peek(): Char {
            if (atEnd) fail("unexpected end of input")
            return s[pos]
        }

        private fun expect(c: Char) {
            if (peek() != c) fail("expected '$c' but found '${s[pos]}'")
            pos++
        }

        fun readValue(): Any? {
            skipWhitespace()
            return when (val c = peek()) {
                '{' -> readObject()
                '[' -> readArray()
                '"' -> readString()
                't' -> readLiteral("true", true)
                'f' -> readLiteral("false", false)
                'n' -> readLiteral("null", null)
                else -> if (c == '-' || c in '0'..'9') readNumber() else fail("unexpected '$c'")
            }
        }

        private fun readLiteral(word: String, value: Any?): Any? {
            if (!s.startsWith(word, pos)) fail("expected '$word'")
            pos += word.length
            return value
        }

        private fun readObject(): Map<String, Any?> {
            expect('{')
            val out = LinkedHashMap<String, Any?>()
            skipWhitespace()
            if (peek() == '}') { pos++; return out }
            while (true) {
                skipWhitespace()
                val key = readString()
                skipWhitespace()
                expect(':')
                out[key] = readValue()
                skipWhitespace()
                when (peek()) {
                    ',' -> pos++
                    '}' -> { pos++; return out }
                    else -> fail("expected ',' or '}'")
                }
            }
        }

        private fun readArray(): List<Any?> {
            expect('[')
            val out = ArrayList<Any?>()
            skipWhitespace()
            if (peek() == ']') { pos++; return out }
            while (true) {
                out.add(readValue())
                skipWhitespace()
                when (peek()) {
                    ',' -> pos++
                    ']' -> { pos++; return out }
                    else -> fail("expected ',' or ']'")
                }
            }
        }

        private fun readString(): String {
            expect('"')
            val sb = StringBuilder()
            while (true) {
                if (atEnd) fail("unterminated string")
                when (val c = s[pos++]) {
                    '"' -> return sb.toString()
                    '\\' -> {
                        if (atEnd) fail("unterminated escape")
                        when (val e = s[pos++]) {
                            '"' -> sb.append('"')
                            '\\' -> sb.append('\\')
                            '/' -> sb.append('/')
                            'b' -> sb.append('\b')
                            'f' -> sb.append('')
                            'n' -> sb.append('\n')
                            'r' -> sb.append('\r')
                            't' -> sb.append('\t')
                            'u' -> {
                                if (pos + 4 > s.length) fail("truncated \\u escape")
                                val hex = s.substring(pos, pos + 4)
                                val code = hex.toIntOrNull(16) ?: fail("bad \\u escape '$hex'")
                                sb.append(code.toChar())
                                pos += 4
                            }
                            else -> fail("unknown escape '\\$e'")
                        }
                    }
                    else -> sb.append(c)
                }
            }
        }

        /** Integers come back as Long, anything with a fraction or exponent as Double. */
        private fun readNumber(): Any {
            val start = pos
            if (!atEnd && s[pos] == '-') pos++
            while (!atEnd && s[pos] in '0'..'9') pos++
            var floating = false
            if (!atEnd && s[pos] == '.') {
                floating = true
                pos++
                while (!atEnd && s[pos] in '0'..'9') pos++
            }
            if (!atEnd && (s[pos] == 'e' || s[pos] == 'E')) {
                floating = true
                pos++
                if (!atEnd && (s[pos] == '+' || s[pos] == '-')) pos++
                while (!atEnd && s[pos] in '0'..'9') pos++
            }
            val text = s.substring(start, pos)
            if (text.isEmpty() || text == "-") fail("malformed number")
            return if (floating) {
                text.toDoubleOrNull() ?: fail("malformed number '$text'")
            } else {
                text.toLongOrNull() ?: text.toDoubleOrNull() ?: fail("malformed number '$text'")
            }
        }
    }
}

// --- typed access, so callers don't cast everywhere ------------------------

internal fun Any?.asObject(where: String): Map<*, *> =
    this as? Map<*, *> ?: throw MiniJson.SyntaxException("$where is not an object")

internal fun Any?.asArray(where: String): List<*> =
    this as? List<*> ?: throw MiniJson.SyntaxException("$where is not an array")

internal fun Map<*, *>.string(key: String, where: String): String =
    this[key] as? String
        ?: throw MiniJson.SyntaxException("$where is missing string field '$key'")

internal fun Map<*, *>.stringOrNull(key: String): String? = this[key] as? String

internal fun Map<*, *>.int(key: String, where: String): Int = when (val v = this[key]) {
    is Long -> v.toInt()
    is Double -> v.toInt()
    else -> throw MiniJson.SyntaxException("$where is missing numeric field '$key'")
}

internal fun Map<*, *>.intOrDefault(key: String, default: Int): Int = when (val v = this[key]) {
    is Long -> v.toInt()
    is Double -> v.toInt()
    else -> default
}
