#!/usr/bin/env python3
"""
Builds the Nonogram mark: the letter N drawn as a solved 5x5 nonogram.

The rest of the gi-os Light collection sets its first letter in Public Sans on a
black square. A puzzle app can do better than a typeface: this draws the same
letter, but as filled cells on a grid, so the mark states what the tool is. Gaps
between cells are what make it read as a grid rather than a blocky glyph, and at
small sizes they are the first thing to disappear — hence the deliberately
generous gap ratio below.

Outputs:

    assets/icon.png                                    1024 square, for the repo
    tool/src/main/res/drawable/loading_text_icon.xml    the splash mark

LightOS tools have no launcher icon. The splash drawable is the only place a tool
shows a mark of its own, and it overrides the drawable of the same name in
sdk:client because resources in the application module win over a library's.

    python3 tools/generate_icon.py
"""
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent

# The letter N as a 5x5 nonogram. Legible at 5x5, which 6x6 and 4x4 are not:
# 4 columns can't hold two stems plus a diagonal, and 6 makes the diagonal
# staircase look like a mistake.
PATTERN = [
    "#...#",
    "##..#",
    "#.#.#",
    "#..##",
    "#...#",
]

# Fraction of the canvas the grid spans. Leaves a margin so the mark doesn't
# crowd the edge when LightOS scales it down.
GRID_SPAN = 0.64

# Gap between cells as a fraction of the cell pitch. Below about 0.10 the cells
# merge into a solid glyph at small sizes and the grid reading is lost.
GAP_RATIO = 0.14

# The SDK's own splash drawable is a 240 square, so this one has to be too.
VIEWPORT = 240


def cells():
    """Yield (row, col) of every filled cell, top-left origin."""
    for r, line in enumerate(PATTERN):
        for c, ch in enumerate(line):
            if ch == "#":
                yield r, c


def geometry(size: float):
    """Return (origin, pitch, cell) in the units of a `size` square canvas."""
    n = len(PATTERN)
    span = size * GRID_SPAN
    pitch = span / n
    cell = pitch * (1.0 - GAP_RATIO)
    origin = (size - span) / 2.0 + (pitch - cell) / 2.0
    return origin, pitch, cell


def write_png() -> None:
    from PIL import Image, ImageDraw

    size = 1024
    img = Image.new("RGB", (size, size), "black")
    draw = ImageDraw.Draw(img)
    origin, pitch, cell = geometry(size)
    for r, c in cells():
        x = origin + c * pitch
        y = origin + r * pitch
        draw.rectangle([x, y, x + cell, y + cell], fill="white")

    out = REPO / "assets" / "icon.png"
    out.parent.mkdir(parents=True, exist_ok=True)
    img.save(out)
    print(f"wrote {out.relative_to(REPO)}")


def write_vector() -> None:
    origin, pitch, cell = geometry(VIEWPORT)

    # One subpath per cell. A single path keeps the drawable to one draw call,
    # which matters more than tidiness on a splash screen.
    parts = []
    for r, c in cells():
        x = origin + c * pitch
        y = origin + r * pitch
        parts.append(
            f"M{x:.2f} {y:.2f}h{cell:.2f}v{cell:.2f}h-{cell:.2f}z"
        )
    path_data = "".join(parts)

    xml = f"""<?xml version="1.0" encoding="utf-8"?>
<!--
    Overrides the drawable of the same name in sdk:client, which is the SDK's
    "loading..." splash mark. Resources in the application module take
    precedence over resources from a library module, so this needs no manifest
    change: LightOS tools have no launcher icon, and the splash is the one place
    a tool can show a mark of its own.

    Generated by tools/generate_icon.py. The letter N as a solved 5x5 nonogram,
    one subpath per filled cell.
-->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="{VIEWPORT}dp"
    android:height="{VIEWPORT}dp"
    android:viewportWidth="{VIEWPORT}"
    android:viewportHeight="{VIEWPORT}">
  <path
      android:pathData="{path_data}"
      android:fillColor="#fff" />
</vector>
"""
    out = REPO / "tool" / "src" / "main" / "res" / "drawable" / "loading_text_icon.xml"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(xml)
    print(f"wrote {out.relative_to(REPO)}")


def main() -> None:
    write_png()
    write_vector()
    print("\n" + "\n".join(
        "".join("##" if ch == "#" else "  " for ch in line) for line in PATTERN
    ))


if __name__ == "__main__":
    main()
